name: Publish Docs

on:
  push:
    branches: 
    - master
    - docs_update
    paths:
    - 'src/docs/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.82.0'
        extended: true
    - name: Build Hugo Docs
      run: |
          cd src/docs
          make build
    - name: Publish to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      env:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_branch: gh-pages
        publish_dir: src/docs/public
